### ISSUE TITLE
[Material Request] Trims Expanded Materials

### ISSUE THREAD

**Issue by Ultimushadow** [Bawnorton/BetterTrims#18]
Trims Expanded is a datapack not a mod, but given that they can be shipped as mods on Modrinth I figured it would be nice to add some compat automatically! I understand that you have a mod made that adds all materials which.. well I don't think I can come up with _that_ many ideas but I can probably come up with 12, those being:

Coal: Every piece adds 5 blocks of radius in which furnaces, blast furnaces, and smokers run twice as fast. 

Dragon's Breath: 25% chance to completely ignore a shulker projectile's damage and levitation. 

Echo Shard: Every piece takes 2 blocks off nearby sculk sensor's detection radius.

Enchanted Golden Apple: Regen one absorption heart every minute per piece with this trim, max number of hearts gained this way is equal to the amount of pieces.

Ender Pearl: Stacking 5% chance when being hit to negate damage, but teleport to a random place like Chorus Fruit.

Fire Charge: All tools/weapons inflict 1 second of fire per piece with this trim.

Glowstone Dust: When initially being affected with a positive potion effect, stacking 20% chance to raise that effect's level by 1.

Leather: Increases step height by .25 blocks per piece, every 2 pieces gain a level of jump boost.

Nether Brick: Wearing 1-2 pieces, Blazes will be neutral but Piglins will always attack you, even if you're wearing gold. Wearing 3-4 pieces, Wither Skeletons will be neutral but Zombie Piglins will always be hostile.

Prismarine Shard: Guardians will ignore the player, having a full set nullifies the Elder Guardian's mining fatigue effect.

Rabbit Hide: Animals will no longer panic around you, including ones that run away without being hit like ocelots/rabbits/foxes.

Slime Ball: Each piece makes the player bouncier and take 25% less fall damage, but take 25% more knockback.

Some of these seem technologically challenging to implement in the way I've described, so if there are functions that won't work here I have plenty of back-up ideas as well. Let me know what you think!

**Comment by Benjamin-Norton** [comment]
I'll give these a look and see how feasible they are. May change some of the effects of the implementation proves to be too complicated.

**Comment by Ultimushadow** [comment]
Yeah as I wrote some of these I was second guessing the ease of implementation. If you would like ideas for any of the added materials in a way that's easier to implement, let me know!

**Comment by Bawnorton** [comment]
Checklist for progress on this

- [ ] Coal
- [ ] Dragon's breath
- [ ] Echo shard
- [ ] Ender pearl
- [ ] Fire charge
- [ ] Glowstone dust
- [ ] Leather
- [ ] Nether brick
- [ ] Prismarine shard
- [ ] Rabbit hide
- [ ] Slime ball

**Comment by Bawnorton** [comment]
Added in 2.0.0
