### ISSUE TITLE
[Bug Report] Server config not controlling clients properly

### ISSUE THREAD

**Issue by Sipxer** [Bawnorton/BetterTrims#21]
When testing your mod for my server I have found out that when editing the data for the server confiq that it does nothing while editing the data for the client side changes the data. this means that people can edit the effects of the armour trim to gain an advantage over other people.

**Comment by Bawnorton** [comment]
Yeah that's something I'll need to look into.

**Comment by Bawnorton** [comment]
Fixed in 2.0.0
