### ISSUE TITLE
[Material Request] Experience Nuggets

### ISSUE THREAD

**Issue by James103** [Bawnorton/BetterTrims#22]
**What materials, and which mods are they from?**
The [Create: Armor Trims](https://modrinth.com/datapack/create-mod-trims) data pack allows the use of Brass, Zinc, Polished Rose Quartz and Experience Nuggets as armor trim materials.

**What should these materials do?**
* Experience Nugget: Killing mobs drops experience nuggets instead of orbs, at reduced efficiency.
  - This applies to all mob kills registered to be by a player wearing the trim.
  - Base ratio is 5 XP for 1 nugget. If needed, this can be modified to scale with the number of pieces worn, capping at 3 XP per nugget with a full set.
  - To get the number of nuggets dropped, first divide the amount of XP that would be dropped by the number of XP per nugget, then award the whole-number part. If a fractional part remains, that represents the _chance_ of an additional experience nugget.

_Edited to clarify calculations and make the idea a tiered set bonus like most other trims._

**Comment by Bawnorton** [comment]
Not Planned (may revisit)
