### ISSUE TITLE
[Bug Report] Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by FatPorpoise** [Bawnorton/BetterTrims#24]
**Expected Behaviour**
I guess it should not crash

**Actual Behaviour**
Game crashed while in crafting inventory (I was crafting boats, nothing mod related)
Second crash while standing still (both times in range of a beacon with [Beacon Overhaul](https://github.com/ChloeDawn/BeaconOverhaul) effects)
Third crash - in the end, no beacon (all three times I was also using this mod [TrimsEffects](https://modrinth.com/mod/trimseffects)
with haste bonus)

**Steps to Reproduce**
Unknown yet, will update if I find it out
Seems to occur randomly

**What version of the mod are you using**
2.0.0

**Helpful Files**
[crash-2023-09-28_23.06.37-client.txt](https://github.com/Bawnorton/BetterTrims/files/12754001/crash-2023-09-28_23.06.37-client.txt)
[crash-2023-09-28_23.20.24-server.txt](https://github.com/Bawnorton/BetterTrims/files/12754147/crash-2023-09-28_23.20.24-server.txt)
[crash-2023-09-29_02.27.37-client.txt](https://github.com/Bawnorton/BetterTrims/files/12754828/crash-2023-09-29_02.27.37-client.txt)

- latest.log
[latest.log](https://github.com/Bawnorton/BetterTrims/files/12754831/latest.log)

**Comment by FatPorpoise** [comment]
I was using redstone trim on all armor parts

**Comment by Bawnorton** [comment]
I've found the issue and patched in 2.0.1, I forgot that minecraft is picky about when you access it's random number generator.
