### ISSUE TITLE
[Bug Report] incompatibility with Trims Expanded

### ISSUE THREAD

**Issue by peow** [Bawnorton/BetterTrims#28]
**Expected Behaviour**
Armor with materials from Trims Expanded give effects to the player

**Actual Behaviour**
i downloaded the AllTheTrims mod, but I didn't like not being able to configure it, i think it's very strange to be able to use a stick as a Trim, so I installed **Trims Expanded**, a mod that only adds a few items such as materials for Trims, but when I place the Trim on the armor with the material, the BetterTrims mod doesn't give the effect, as if the armor was not trimmed, 
so redstone, iron and other Vanilla itens **works** as expected, but netherbrick **dont** make blazes ignore me, enderpearl **dont** make me take damage in water *(and it's not a problem with the mod settings)*, these new itens only work with AllTheTrims

I liked Trims Expanded because it only adds the items that give effects, and searching in the "Issues", I saw that BetterTrims originally had the "AddedVanilla" materials added because of Trims Expanded, so I imagine it would still be compatible
https://github.com/Bawnorton/BetterTrims/issues/18

**Steps to Reproduce**
- Download BetterTrims
- Download Trims Expanded
- Try to receive effects with an not-vanilla Trim

**What version of the mod are you using**
BetterTrims v2.0.5, Trims Expanded v1.3.0 (mod version, not datapack)

if you will fix this, pls make an update to Fabric 1.20.1

**Comment by NolanHewitt** [comment]
Can confirm the same issue here, they dont work together on 1.20.1 : (

**Comment by Bawnorton** [comment]
Yes, I will be addressing this and #29, and the other open issues / prs when the holidays end, sorry for the delay, happy new year.

**Comment by NolanHewitt** [comment]
No worries about the delay, enjoy your holiday, and thank you for making this mod!

**Comment by Bawnorton** [comment]
Fixed in 2.1.0
