### ISSUE TITLE
[Bug Report] list of bugs I found

### ISSUE THREAD

**Issue by peow** [Bawnorton/BetterTrims#29]
**What version of the mod are you using**
BetterTrims v2.0.5 (Fabric 1.20.1)
AllTheTrims v3.3.7

- latest.log
[latest.log](https://github.com/Bawnorton/BetterTrims/files/13562811/latest.log)

I liked your mod, I tested it to put it in my modpack and ended up finding some problems:

- Copper Material - if you have full armor with Copper Trim but have your boots enchanted with Depth Strider 3, your speed will be reduced, I saw it said that it doesn't stack with Depth Strider, but dont have sense you be slower, you should just ignore Depth Strider's effect if you're already faster than the enchantment could make you

- Iron Material - any tool with Efficiency 4 or 5 can insta-mine sand, red sand, gravel, dirt, even if it is configured to only increase mining speed by 0.05, even if you only have one piece of armor equipped
(with Efficiency 3 and only one piece of armor with Iron Material, any tool break dirt/sand very quickly, but do not insta-mine)

- Dragon Breath Material - I ask that you ensure that the Player who is using the armor with Dragon Breath Material does not get the effects that he is sharing, because if for example I have the Speed effect and I drink a bucket of milk to get it out, as soon as I lose the effect I will get it again because of the particles around me, this is annoying

- Leather Material - crouching has not worked correctly when using armor with Leather Material, because if for example you climb 3 blocks in height, when trying to go to the side of a block crouching to avoid falling, you will still fall, as long as you are falling the same number of blocks you can climb

- Enderpearl Material - I'm facing an incompatibility problem with some other mod that I don't know which one, but when I touch the water using Enderpearl Trim armor I start to teleport without stopping, even when I'm already out of the water, I realized that It doesn't happen when I test the mod alone without any other mod along with it, do you have any idea what could be causing this?

- Silver Material - it is only supposed to work at night, but it works all the time in the Nether and The End, even if it is daytime in the overworld, another thing is that the Night Vision that Silver gives to the player is not recognized by the ComplementeryReimagined shader, this shader recognizes the standard Minecraft Night Vision effect but does not recognize the one in your mod, I understand if it is not possible to fix this

- Slime Material - the increased Knockback doesn't seem to be happening, I spawned a zombie with a sword with a Knockback 2 enchantment and the armor with Slime Material hasn't caused me to be thrown further when the zombie attacks me

*/summon zombie ~ ~ ~ {HandItems:[{id:"minecraft:iron_sword",Count:1b,tag:{Enchantments:[{id:"minecraft:knockback",lvl:2s}]}},{}]}*

I'm also experiencing an incompatibility problem with Slime Material, as it hasn't removed my fall damage, I don't know which other mod is causing this

Fire Charge Material - when a zombie attacks me and it starts to catch fire, my game crashes
[crash-2023-12-05_13.33.38-server.txt](https://github.com/Bawnorton/BetterTrims/files/13562798/crash-2023-12-05_13.33.38-server.txt)

--------

When using BetterTrims together with AllTheTrims (your other mod that allows all armor to receive Trims and all items to be used as Trims) some bugs happen

Elytra + Netherite Shield (from Guarding mod) count as armor just when you hold them, for example if I'm using Redstone Material on Elytra and Netherite Shield, I gain speed just by leaving them in my hand, without even equipping Elytra, and that It's a problem, because I can put the 4 pieces of armor with Redstone Material + Elytra with Redstone Material in my hand and the Netherite Shield with Redstone Material in the off-hand, and I'll have a much higher speed than with just the armor

In these images I'm using armor with Netherite Material and an Elytra with Netherite Material, I configured it so that each Trim gives me 25% immunity to fire, so 4 pieces give me complete immunity, notice that with 3 armor equipped and nothing selected in the Hotbar I still catch fire, but when selecting Elytra I become immune to lava

![2023-11-30_21 19 19](https://github.com/Bawnorton/BetterTrims/assets/105888751/2cd0080c-3d42-4be2-b21b-c88c8cec501b)
![2023-11-30_21 19 25](https://github.com/Bawnorton/BetterTrims/assets/105888751/8bf66948-9fbd-4a1d-bd39-ccfa5a2a5187)

*this problem also happens with Custom Elytras from Clutter mod

my suggestion is that only what is equipped in the armor slots gives you effects, I believe that the Netherite Shield should not give you effects either, as it just stays in your hand and is not equipped on your body, but if you want to let it the Netherite Shield still gives effects to the Player, I would recommend putting a limit on how many pieces you can receive each effect, for example you can only receive speed effects from 4 pieces, so if I have full armor (4 pieces) + the Netherite Shield on hand, I will only receive the x4 effect, not x5, so if someone wants to use the Netherite Shield, they will have to put another Trim Material on it, such as Iron or Silver

-------
*The "Revert" option in the mod settings is not returning the numbers to the default, but to the previous settings

![image](https://github.com/Bawnorton/BetterTrims/assets/105888751/f7e29d38-4b38-4979-bc8c-419a62b375b2)

*I would like to ask if it was possible to deactivate the effects of all Materials, currently only Coal and some others that can be deactivated

I found some bugs in your other mod **AllTheTrims** too and I will post it on GitHub, I ask you to check it out too

and i beg you, do an update to **1.20.1** in **Fabric Loader 0.14.22** , I would really like to be able to use BetterTrims in my modpack

**Comment by Bawnorton** [comment]
Thank you for the comprehensive list of bugs. I'll look into addressing these after exam season.

**Comment by Bawnorton** [comment]
For the sake of tracking: 
- [ ] Copper - Swim Speed Fixing
- [ ] Iron - Mining Speed Balancing 
- [ ] Dragon's Breath - Don't apply to self
- [ ] Leather - Stepping down
    - I believe this is a consequence of how vanilla calculates when you can drop, for instance, you can sneak walk down slabs
- [ ] Ender pearl - Constant tp'ing
    - Not sure what causes that but I think I can work around that
- [ ] Silver - Don't apply in dimensions that don't have a day/night cycle
    - Give player night vision effect instead of increasing block light 
- [ ] Slime - Fix knockback velocity 
- [ ] Only apply effects if item is in the correct slot
- [ ] Revert option is from another mod, YACL, I can look into adding a defaults button but that will need to be made as a pr to that mod
- [ ] Add de-activate option for all effects

**Comment by Bawnorton** [comment]
Fixed in 2.1.0
