### ISSUE TITLE
[Bug Report] Incompatible with 'StackedTrims' 

### ISSUE THREAD

**Issue by EmojiPati** [Bawnorton/BetterTrims#32]
On the StackedTrims Mod's Page it states that it is Compatible with this Mod, but when I installed both mods on the server, the 'better trims' mod stopped working.

I could break a deepslate instantly under normal conditions, but when I installed that mod, I could hardly break even a stone.

also when I downloaded the mod this text disappeared.

![2024-01-06_03 33 40](https://github.com/Bawnorton/BetterTrims/assets/49492351/da841d32-e47f-4fb4-8a7a-58b2e217e228)

**Comment by Bawnorton** [comment]
I'll look into this, thanks
