### ISSUE TITLE
Mining faster bug

### ISSUE THREAD

**Issue by TreeGar2009** [Bawnorton/BetterTrims#33]
Dirt mining
When you mine the dirt with a full set of faster mining armor and a diamond or netherite shovel it should break

Dirt not breaking
When using the armor the dirt would not break and would instead enter a glitched state where I could break it over and over again. It fixed itself as soon as I took off the armor
Steps to Reproduce
- Step 1 Get a full set of faster mining armor {Armor with the iron trim}
- Step 2 Get a diamond or netherite shovel

1.20.1

**Comment by Bawnorton** [comment]
Fixed in 2.1.0
