### ISSUE TITLE
[Bug Report] Added vanilla materials cannot be used

### ISSUE THREAD

**Issue by Skrublord540** [Bawnorton/BetterTrims#35]
**Actual Behaviour**
No matter which specific trim items are enabled/disabled, the added vanilla trim materials **(ex. coal, dragons breath)**  just don't work in the smithing table. Even REI crafting recipe doesn't show. 
(Vanilla materials work perfectly. I have never used the modded ones, so I don't know about them.)

I'm not too worried if it is unfixable, or if I'm doing something wrong, had this issue on my last world, and just didn't pay any mind, but if it is user error, like an incompatible mod, I would like to know.

**What version of the mod are you using**
3.2.1 on 1.20.1
Note-
Using quilt loader 0.23.1, can confirm same issue on fabric 0.15.6 from previous world.

- latest.log
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14161281/latest.log)

**Comment by Bawnorton** [comment]
Yes, BetterTrims only provides the effects, if you want to use the effects for other materials then you will need to add a datapack that adds those materials or use my other mod AllTheTrims, which allows the use any material.
