### ISSUE TITLE
Copper Trim Buff Completely OP Stacking incorrectly?

### ISSUE THREAD

**Issue by alexweber** [Bawnorton/BetterTrims#36]
**Expected Behaviour**
The Copper Trim effect is supposed to give a small configurable speed to swim speed

**Actual Behaviour**
Regardless of whether the copper trim buff is enabled or not or what the % is configured to be, when paired with Depth Strider (and also with a redstone trim - probably irrelevant) the boost is completely unreasonable and can't be reduced.  Even disabling copper entirely won't make it go away.  The only way to not swim at the speed of light is to trim with another material instead.

Now that I think about it maybe the bug has to do with once applied a trim is not respecting updating config values?

Either way, unfortunately it's just too fast and not fair/playable in the current state... 

**Steps to Reproduce**
- Enchant boots with Depth Strider 3
- Trim them with any Copper trim
- Optional. Trim another piece with redstone for parity with my test/

**What version of the mod are you using**
2.2.3

Thanks!

**Comment by Bawnorton** [comment]
Are you playing with any other mods? I can't replicate this behaviour

**Comment by NolanHewitt** [comment]
I can replicate this. Movement speed with depth strider and 4 pieces of copper trim armor makes me move at the speed of light.

https://github.com/Bawnorton/BetterTrims/assets/52480898/e4b55b72-f8b5-4b46-8ee5-badaa7510d5e

**Comment by NolanHewitt** [comment]
I think I found a fix, in the config set "copper_swim_speed_increase": 0.005, instead of the default of 0.05. Feels much more like a 5% increase per piece with this.

**Comment by alexweber** [comment]
@NolanHewitt Nice!  Doing that didn't work for me but I think there's a potential issue where once you trim an armour with certain config values it sticks to them cause with a single piece only and 0.00005 it was still lightspeed, haven't had the opportunity to test more though

**Comment by Bawnorton** [comment]
Default value adjusted in next release
