### ISSUE TITLE
[Bug Report] I cant add modded vanilla materials!

### ISSUE THREAD

**Issue by vlad8599** [Bawnorton/BetterTrims#37]
**Expected Behaviour**
I should be able to add nether bricks, leather, etc. as "base material" of trims.

**Actual Behaviour**
Station for work with upgrades only accept materials from vanilla game list, not leather, nether bricks, etc. - you can use diamonds, iron, redstone, etc., but you cant put anything other into slot. Help me, please!

**Steps to Reproduce**
Just try to put the trims with Added Vanilla Materials and you will see.

**What version of the mod are you using**
2.2.3, but with Minecraft 1.20.4

**Helpful Files**
Drag and drop these files here to help me figure out what broke.

- latest.log
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14296670/latest.log)

**Comment by Bawnorton** [comment]
Better trims provides the effects for other materials but doesn't provide the trims themselves. You'll want to use a datapack that adds those like Trims Expanded or my AllTheTrims mod
