### ISSUE TITLE
[Bug Report] "high" Server thread use (Spark Profile)

### ISSUE THREAD

**Issue by peow** [Bawnorton/BetterTrims#38]
using Spark to see what is causing lag in my singleplayer world, BetterTrims appears almost on the top list, showing this:
![image](https://github.com/Bawnorton/BetterTrims/assets/105888751/174aae1b-8016-4121-ab8c-c63220c9b43b)

Spark Profile Link - https://spark.lucko.me/48kXm00pPM

this is normal? there is no way to decrease it?

- latest.log
  - 
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14335404/latest.log)

**Comment by Bawnorton** [comment]
I'll look into this when I am available

**Comment by Bawnorton** [comment]
1.20.1 is no longer being developed; 1.21 version solves this via the component system
