### ISSUE TITLE
[Feature Request] pillagers shouldnt ignore you when you hit them

### ISSUE THREAD

**Issue by MoreCaveSounds** [Bawnorton/BetterTrims#39]
currently if you have the platinum trim, illagers will ignore you as they should (works even with modded illagers which is nice)

but they ignore you COMPLETELY, even if you hit them
unless this was intentional, i think they should attack you if you hit them, additionally when you hit one illager all illagers near should also attack you (pack mentality)

**Comment by Bawnorton** [comment]
I'll look into this when I am available

**Comment by Bawnorton** [comment]
Changed the implementation to allow the "ignorable" entities to retaliate, group retaliation would require rather invasive changes as some of these entities don't have the concept of group revenge like zombie piglins and I don't have a whole lot of time on my hands to implement that system.
