### ISSUE TITLE
[Bug Report] Amethyst doesnt gives me a potion buff

### ISSUE THREAD

**Issue by vlad8599** [Bawnorton/BetterTrims#40]
Expected Behaviour
I should see that my + potions(force, regeneration, etc.) working almost twice longer.

Actual Behaviour
It doesnt have any effect, if you will check timer, you will see that potion have its usual duration time(like 21 second for a Regeneration 2 potion).

Steps to Reproduce
Just add trim with amethyst to armor and you will see. Full armor set with amethyst.

What version of the mod are you using
2.2.3, but with Minecraft 1.20.4

Helpful Files
Drag and drop these files here to help me figure out what broke.
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14351287/latest.log)

**Comment by Bawnorton** [comment]
Amethyst doesn't increase the duration of the effect, it just gives positive effects a chance to not tick down a second. Time the effects externally and they'll last longer.

**Comment by Bawnorton** [comment]
Every second there is a % chance that the duration of the potion effect doesn't decrease.

So instead of the potion effect going `5 -> 4 -> 3 -> 2 -> 1 -> 0`, it can go `5 -> 4 -> 4 -> 3 -> 2 -> 2 -> 1 -> 0` making it last 7 seconds instead of 5.

**Comment by vlad8599** [comment]
Its not related to time on timer?

**Comment by Bawnorton** [comment]
The time on the timer will go down slower.
Give yourself resistance for 30 seconds, set a 30 second timer. Your timer will end about 10 seconds before the effect ends

**Comment by vlad8599** [comment]
Just tested with a few different effects(resistance, glowing, poison). It doesnt work! 30 seconds timer - and no slowing down for positive or faster for negative effects. Here is a log.
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14360392/latest.log)
