### ISSUE TITLE
1.20.4 patch?

### ISSUE THREAD

**Issue by vlad8599** [Bawnorton/BetterTrims#41]
**Expected Behaviour**
All effects should be working fine in 1.20.4. OR game crashes.

**Actual Behaviour**
After some tests I see that most things are broken, if you launch mod on game version higher than 1.20.1.
Game actually launches and you can play normally, but most of the effects from materials doesnt work.
For example, amethyst gives me a glowing and redstone\copper actually makes me moving faster on earth\underwater, but faster mining from iron, buffs to potions from amethyst, discounts from villagers for emeralds - all this stuff just doesnt work. Other materials not tested, but most probably, situation is same.

Can you make a patch for 1.20.4 support, please?

**Steps to Reproduce**
- Install this mod on 1.20.4 and launch your game.
- Try to use different materials on your armor(first of all emerald, amethyst and iron).
- Test all effects that you expecting to have.

**What version of the mod are you using**
2.2.3

**Helpful Files**
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14360956/latest.log)

**Comment by limemango3** [comment]
I have no issue with the mod on 1.20.1 and the game version on 1.20.4, maybe its caused by other mods

**Comment by Bawnorton** [comment]
Not planned
