### ISSUE TITLE
[Bug Report] Vanilla+ trims can't be put into the smithing table.

### ISSUE THREAD

**Issue by ShyAndSleepy** [Bawnorton/BetterTrims#46]
**Expected Behaviour**
You should be able to use the smithing table to apply vanilla+ trim materials.

**Actual Behaviour**
You cannot apply vanilla+ trim materials to items

**Steps to Reproduce**
- Get a vanilla+ trim material (like slime, echo shards, rabbit hide)
- Attempt to apply it to a piece of armour.
- Realise that it does not go into the slot

**What version of the mod are you using**
2.2.3

**Helpful Files**
Drag and drop these files here to help me figure out what broke.

- latest.log
  - Found in `.minecraft/logs`

**Comment by Bawnorton** [comment]
See #37
