### ISSUE TITLE
[Bug Report] Crash with Iris 1.7.10-snapshot for Distant Horizons 

### ISSUE THREAD

**Issue by jukarr** [Bawnorton/BetterTrims#47]
**Expected Behaviour**
The game should launch as per usual - it does so when Better Trims is disabled.

**Actual Behaviour**
Game crashes, the crash report mentions the kiwi library mod

**Steps to Reproduce**
- Hard to say as it's not related directly to kiwi - probably an incompatability with another mod. The game starts fine with just the Better Trims mod disabled

**What version of the mod are you using**
2.2.3

**Helpful Files**

[crash-2024-03-29_14.59.33-client.txt](https://github.com/Bawnorton/BetterTrims/files/14805038/crash-2024-03-29_14.59.33-client.txt)
[latest.log](https://github.com/Bawnorton/BetterTrims/files/14805040/latest.log)

**Comment by FallconTXoC** [comment]
I can push a fix for you, Iris changed their namespace from net.coderbot to net.irisshaders and that's what making BetterTrims unable to find MixinGameRenderer_NightVisionCompat

**Comment by Bawnorton** [comment]
Yes I'm aware. See above comment for why I've not addressed this. 
If you are knowledgeable on how to conditionally apply mixins based on mod version feel free to add an additional mixin for the experimental iris builds (you can't just change the namespace as that would break compat with the current stable versions)

**Comment by muon-rw** [comment]
Iris 1.7.0 is now released.

**Comment by Bawnorton** [comment]
Fixed in 2.3.1
