### ISSUE TITLE
Missing isDamageable check on itemstacks cause non-damageable items to get damage nbt and be unstackable

### ISSUE THREAD

**Issue by Linguardium** [Bawnorton/BetterTrims#49]
https://github.com/Bawnorton/BetterTrims/blob/1a40707513b7c1ec491a42d7a85773192cfacba5/src/main/java/com/bawnorton/bettertrims/mixin/SmithingScreenHandlerMixin.java#L26-L27

**Comment by Bawnorton** [comment]
Fixed in next releease
