### ISSUE TITLE
Suggestion: Each Trim Design Set Bonus has different buffs

### ISSUE THREAD

**Issue by ConqAra** [Bawnorton/BetterTrims#5]
Have small attribute additions / buffs based on what trim designs you're using!

full set of tide gives you longer water breathing,
full set of ward gives you more armor,
full set of ribs give you more damage,
etc!
Need help with ideas, but if you're down for this we can go over them

**Comment by Benjamin-Norton** [comment]
I'll give it a look and see if I like the balance

**Comment by Benjamin-Norton** [comment]
I'll give it a look and see if I like the balance

**Comment by ConqAra** [comment]
I recommend for just it only applying to full sets as a reward for having all four trims, but if you think otherwise then you have it smaller buffs

Tide drops from elder guardians so it can give you longer water breathing or something of that sort.

Ward is from ancient city, seems defensive/tanky like so it gives you more armor.

Ribs relate to the nether, can be a more offensive buff, such as increasing fire damage.

Sentry can relate to bows such as damage with bows/crossbows, accuracy, or something alike.

Snout relates to piglins, but gold trims already do that UNLESS you wanna swap it with extra attack speed, if not then snout has it.

Spire relates to the end, a later game template. could relate to flying speed or maybe extra health.

Vex relates to vexes and woodland mansions, probably gives extra attack damage.

Wild Armor relates to the jungle, being wild could increase your haste when mining/using tools, so extra haste.

These are all shots in the dark for ideas, but tell me what you think!

**Comment by JuiceyBeans** [comment]
> Snout relates to piglins, but gold trims already do that UNLESS you wanna swap it with extra attack speed, if not then snout has it.

Could give haste using Snout? After all, gold tools do mine faster. A full set could grant Haste 1 permanently, or increase attack speed

**Comment by ConqAra** [comment]
Another suggestion I have is to config an optional replacement, where instead of what material you use for trims, its the trim designs themselves. Doing both may be a little too much afterall

**Comment by Bawnorton** [comment]
Out of scope
