### ISSUE TITLE
Material not working on armor, 

### ISSUE THREAD

**Issue by SquishyOwO** [Bawnorton/BetterTrims#51]
When i go to trim my armor with nether brick it wont go into the ingot slot in the smithing table, am i missing something or is this just a bug?

**Comment by SquishyOwO** [comment]
Never Mind Figured It Out, I Don't Know how to close this request im new to github

**Comment by Bawnorton** [comment]
Yeah you'd need to use another mod or datapack to allow the modded materials to be applicable
