### ISSUE TITLE
[Bug Report] problems with Ender Pearl Trim 

### ISSUE THREAD

**Issue by peow** [Bawnorton/BetterTrims#53]
thank you very much for continuing to update your mod
the update 2.3.0 came with some accidental problems (which are still present in the latest version)

* Ender Pearl's trim is giving immunity to any type of damage to the Player (even Void damage)
![image](https://github.com/Bawnorton/BetterTrims/assets/105888751/e855e41b-876a-413c-ad41-d90949d432c5)

To test, just equip one piece of armor with Ender Pearl material, and try to take damage

/summon minecraft:creeper

/summon enderman

the Player just doesn't take damage and he doesn't teleport most of the time, but he always teleports in rain and water (but without taking damage)

* and another problem I found, if you go in the middle of an ocean, with no blocks nearby, you get stuck in the water without being able to move to the sides, as it seems like the Player is trying to teleport but has nowhere to go.

![image](https://github.com/Bawnorton/BetterTrims/assets/105888751/8dda15d9-2edf-494a-b249-cbb5a148a9ec)

my config:
![image](https://github.com/Bawnorton/BetterTrims/assets/105888751/a1d954f2-8c8c-47fa-b578-ca43e46b007c)

even low values are giving you immunity

* also the skeleton's arrows are reflected
![image](https://github.com/Bawnorton/BetterTrims/assets/105888751/35464688-e0c8-4af8-ba13-b2c72a0ff320)

-----------------

I tested it on an instance with only BetterTrims, TrimsExpanded, ModMenu, Fabric API and YACL on Fabric 1.20.1

- latest.log
  - https://mclo.gs/Q5qvTnd

**Comment by Bawnorton** [comment]
Fixed in the latest (and last 1.20.1) build
