### ISSUE TITLE
1.21 (pls add 1.21)

### ISSUE THREAD

**Issue by CheeseisJuicy** [Bawnorton/BetterTrims#55]
update mod to 1.21

**Comment by Bawnorton** [comment]
![image](https://github.com/Bawnorton/BetterTrims/assets/18416784/72390ba4-9123-44c7-b30d-a77916b3f522)

**Comment by Bawnorton** [comment]
Its on my todo as a part of the complete rewrite

**Comment by traceover** [comment]
would it be possible just to update without rewrite? My friends and I just started a server in 1.21 and really want to use this mod!

**Comment by Bawnorton** [comment]
No, the system this uses was completely removed in 1.20.4 with the nbt -> components change

**Comment by Bawnorton** [comment]
Also there are a lot of bugs that I need to address and am already in the process of doing so

**Comment by traceover** [comment]
I see. Well, thanks for the quick replies

**Comment by LalyosHUN** [comment]
So when can we expect the big update?

**Comment by Bawnorton** [comment]
When it's ready
