### ISSUE TITLE
[Bug Report] Leather Trim stops working in end

### ISSUE THREAD

**Issue by Shyzle** [Bawnorton/BetterTrims#56]
•Leather trim providing step up on one piece of gear

•Step up not working after entering end dimension, doesn't work until client relaunch.

•Bettertrims 2.2.2 - being used in the prominence 2 rpg mod pack MC 1.20.1

[latest.log](https://github.com/user-attachments/files/16025345/latest.log)

I have not attempted to just trying with the mod alone outside of the modpack but i figured i'd toss this in here just in-case it may be something on your mod's side. Logs are just after entering the end and the step up stops working.

**Comment by Bawnorton** [comment]
1.20.1 is no longer being developed
