### ISSUE TITLE
[Material Request] Cincinnasite, Nether Ruby, Zinc

### ISSUE THREAD

**Issue by smirkjuice** [Bawnorton/BetterTrims#57]
**What materials, and which mods are they from?**

Better Nether: Cincinnasite
Better Nether: Nether Ruby
Create: Zinc

**What should these materials do?**

- Cincinnasite: could make trading with Piglins better, like increase the chance of Ender Pearls and rarer items by 5 or 10%, but shouldn't be stackable (If it was stackable, for example, 4 armour pieces with this trim would make give Splash Potion of Fire Resistance a 40% drop rate).

- Nether Ruby: could give the armour piece Ruby's Fire from Better Nether, but shouldn't be stackable (Ruby's Fire gives the armour piece Thorns but with fire).

- Zinc: could increase the RPM of contraptions within a 20 block radius by 10%, should be stackable, but any piece after the first should increase by 5%

**Comment by Bawnorton** [comment]
Not Planned (may revisit)

**Comment by smirkjuice** [comment]
all good :)
