### ISSUE TITLE
[Bug Report] Using BetterTrims breaks the Tuning Fork detection range from Spelunkery

### ISSUE THREAD

**Issue by mintynoura** [Bawnorton/BetterTrims#58]
**Expected Behaviour**
The range would stay normal and would follow the value in Spelunkery's config file.

**Actual Behaviour**
When running BetterTrims with the mod Spelunkery, the range of its Amethyst Tuning Forks is reduced to less than 8 blocks (from an original value of over 128). Modifying the range value in Spelunkery's config does not seem to change anything. This makes Tuning Forks difficult to use.

**Steps to Reproduce**
- Step 1: Install Spelunkery, test Tuning Fork range
- Step 2: Install BetterTrims, test the range again

**What version of the mod are you using**
BetterTrims version: 2.3.1
Spelunkery version: 1.20.1-0.3.5

**Helpful Files**

https://github.com/user-attachments/assets/a04af06f-5ca2-40c1-b88b-7c0155573a98

- latest.log
  [Here](https://mclo.gs/3efkucb), but it does not seem to mention any errors about this.

**Comment by Bawnorton** [comment]
1.20.1 is no longer being developed
