### ISSUE TITLE
fabric api required on neoforge :skull: 

### ISSUE THREAD

**Issue by VaporeonScripts** [Bawnorton/BetterTrims#59]
![image](https://github.com/user-attachments/assets/60ba1dac-a42d-40c1-8a01-fef3764be569)

**Comment by Bawnorton** [comment]
Yes, forgeified fabric api is required

**Comment by Bawnorton** [comment]
It has the same modid for compat reasons https://www.curseforge.com/minecraft/mc-mods/forgified-fabric-api

**Comment by VaporeonScripts** [comment]
bruh then it isnt really  a neoforge mod :/

**Comment by Bawnorton** [comment]
I use ffapi to avoid duplicating network code, it is a NeoForge mod, it uses a pre-processor to allow me to generate two jars from one source set. One for NeoForge and one for Fabric. Quit complaining, stop being ungrateful and be happy I ported the mod to NeoForge.

**Comment by Bawnorton** [comment]
https://github.com/Bawnorton/BetterTrims/blob/stonecutter/src/main/java/com/bawnorton/bettertrims/platform/BetterTrimsWrapper.java
