### ISSUE TITLE
Flashing status effect while mining 1.21

### ISSUE THREAD

**Issue by Droow6** [Bawnorton/BetterTrims#61]
Through a process of elimination I arrived at this mod. Pretty sure its this one, but maybe an incompatibility with another mod
 
Clip with no trims, the blue line is caused by "status effect bar" though
https://github.com/user-attachments/assets/38b9b265-0c85-4200-b777-e52daf4c4c12

modlist

![Droow6 09-20-2024 111718PM](https://github.com/user-attachments/assets/87b70643-f923-4d21-b22a-beacba6cc59e)

**Comment by Bawnorton** [comment]
Curious, I'll look into this

**Comment by Bawnorton** [comment]
Fixed in 3.1.0
