### ISSUE TITLE
Auto jump when using mod?

### ISSUE THREAD

**Issue by MikeRafone7** [Bawnorton/BetterTrims#62]
I downloaded the new update but whenever I play I auto jump over blocks, even though the the auto jump is turned of. Any idea why this is?

**Comment by Bawnorton** [comment]
Please confirm that this occurs with only this mod, or produce a minimum set of mods where this occurs as I do not touch anything related to auto jumping

**Comment by MikeRafone7** [comment]
I tested it and it still happend. All I was using was Fabric api, yet another config lib, configurable and better trims and I still had the problem

**Comment by szernex** [comment]
I can reproduce this as well, as with the latest version of BetterTrims 3.1.1-fabric+1.20.1. If I go back to version 2.3.2 it does not happen. Instance is running Minecraft 1.20.1 with Fabric 0.16.5, here is a screenshots of all mods in the instance:
![image](https://github.com/user-attachments/assets/a71b405a-8275-4e8c-be5b-33a667b46385)

It is basically behaving as if auto-step is enabled, even though it shouldn't be. I'm not wearing any gear and vanilla auto-jump is disabled:


https://github.com/user-attachments/assets/89b8ee11-8fc3-4ba1-846f-0e42447fdcd5

**Comment by Bawnorton** [comment]
Ok I think I know what is happening

**Comment by Bawnorton** [comment]
Should be fixed in 3.1.2
