### ISSUE TITLE
Missing lang string "generic_step_height"

### ISSUE THREAD

**Issue by HaXrDEV** [Bawnorton/BetterTrims#68]
![image](https://github.com/user-attachments/assets/a8f72be7-6def-4e98-9ed3-191967711207)

Confirmed to also occur with minimal amount of mods installed.

Mod version: BetterTrims-3.1.3-fabric+1.20.1.jar

**Comment by Bawnorton** [comment]
Thanks, I was bound to miss at least one translation given this mod has over 200

**Comment by Bawnorton** [comment]
Fixed
