### ISSUE TITLE
Prismarine Armor trim Issue 

### ISSUE THREAD

**Issue by SuperKitty369** [Bawnorton/BetterTrims#73]
When you apply the Prismarine Materail to an armor trim, wear it, and gain exp. it cuases all armor to suddly have all enchantments. it doesnt show but its very obvious as suddly ice starts appering from frost walker and you cant take off any armor due to curse of binding. 

How to reproduce 
![Screenshot 2024-10-03 174415](https://github.com/user-attachments/assets/7363b5ef-5d1c-48dd-ad7b-1f44d469442b)

Then, gain exp. 
i have tested this with these mods on the modrinth launcher
- BetterTrims ( V 3.2.2-fabric+1.20.1 )
- All The Trims ( V 3.4.3 )

**Comment by Bawnorton** [comment]
what a bizarre bug, I'll look into it

**Comment by Bawnorton** [comment]
Fixed in 3.2.4
