### ISSUE TITLE
Diamond To Netherite Upgrade 

### ISSUE THREAD

**Issue by SuperKitty369** [Bawnorton/BetterTrims#75]
If you upgrade diamoind armor that has one of the better trims to netherite. it doesnt add the fetaures of netherite.

![image](https://github.com/user-attachments/assets/d75abed9-3012-4501-9a97-9684a6fb8ee2)
![image](https://github.com/user-attachments/assets/a6ac819b-0586-42aa-8af2-0867d4ad47d0)

**Comment by Bawnorton** [comment]
I'll look into that

**Comment by Bawnorton** [comment]
Fixed in 3.2.5, it was actually a bug with vanilla not correctly handling custom attribute modifiers when upgrading to armour that has its own default attribute modifiers
