### ISSUE TITLE
Incompatible with Fabric versions 0.16.5 and newer

### ISSUE THREAD

**Issue by SJM00749** [Bawnorton/BetterTrims#76]
[crash-2024-10-14_02.47.59-client.txt](https://github.com/user-attachments/files/17358056/crash-2024-10-14_02.47.59-client.txt)
[crash-2024-10-14_02.55.06-client.txt](https://github.com/user-attachments/files/17358118/crash-2024-10-14_02.55.06-client.txt)

I was using Better Trims in a small mod pack for personal use with Prism launcher, but it is crashing with newer versions of Fabric, from 0.16.5 up to 0.16.7. I tested this by trying to launch with all mods, then with all other mods disabled besides Fabric API and the other library mods Better Trims needs. Both times it crashed, the logs attached show this. The game however ran with all other mods enabled and Better Trims disabled.

**Comment by Bawnorton** [comment]
Downgrade configurable to 1.3
