### ISSUE TITLE
elytratrims is incompatible with AllTheTrim and causes crashes

### ISSUE THREAD

**Issue by Cindystick** [Bawnorton/BetterTrims#79]
Although BetterTrims is compatible with elytratrims and is also compatible with AllTheTrims (BetterTrims also creates effects for various special materials such as echo fragments, coal, slime balls and even progress interfaces),
However, elytratrims and AllTheTrim were incompatible, and the game crashed directly. After logging in again, all the original forging templates and elywings disappeared

**Comment by Bawnorton** [comment]
Log please

**Comment by Cindystick** [comment]
[Uploading crash-2024-10-16_23.22.36-client.txt…]()

**Comment by Cindystick** [comment]
[2024-10-16-7.log.gz](https://github.com/user-attachments/files/17398342/2024-10-16-7.log.gz)
[latest.log](https://github.com/user-attachments/files/17398343/latest.log)

**Comment by Cindystick** [comment]
I opened another new save to test it, and it still collapsed. Although the elytra can normally attach ten materials that could be attached to the vanilla armor and better trims can function normally, meanwhile the armor can also attach various materials added by all the tirm and better trims can also function, once the elytra is attached to various materials added by all the tirm (such as echo fragments), it will collapse. That is, elytratrims and AllTheTrim are incompatible

**Comment by Bawnorton** [comment]
Update Elytra Trims to 3.5.4

**Comment by Cindystick** [comment]
I did so and updated the versions of the two modules to the latest version, but all the trims itself does not have version 1.21.1, only version 1.21. Is this why it is incompatible with the elytra trims module?

**Comment by Bawnorton** [comment]
no, all 1.21 mods are compatible with 1.21.1 and vice versa

**Comment by Cindystick** [comment]
I downloaded runtimetrims, a new pre-module, and updated all modules of trims type and all pre-modules to the latest version, which finally solved the crash problem. Now the elytra can be normally typed in all the trim(Materials other than ten minerals added).
![2024-10-17_17 59 27](https://github.com/user-attachments/assets/8e0c6282-0c9c-420e-93fc-f2b090e39c94)

**Comment by Bawnorton** [comment]
If you enable the legacy renderer inside runtime trims does it render correctly? If not it's something I missed during testing

**Comment by Cindystick** [comment]
excuse me, how to enable the legacy renderer?
For now, texture rendering of various materials is normal. Different colors appear because of different materials, and different patterns are displayed because of different armor pattern templates
![2024-10-17_21 51 47](https://github.com/user-attachments/assets/a7eb05e1-1460-4667-89fa-2d0a9ff2d865)
![2024-10-17_21 52 05](https://github.com/user-attachments/assets/42871a8e-67b7-478c-9efd-0a437fa3350e)
![2024-10-17_21 52 19](https://github.com/user-attachments/assets/bccb34fd-2f24-4e40-aa75-b31294b52fa1)
![2024-10-17_21 53 31](https://github.com/user-attachments/assets/70982c27-c5bc-4f6e-ab24-7d757cbcd066)
![2024-10-17_21 53 34](https://github.com/user-attachments/assets/8d84791c-b9fe-4fb9-82f1-0cfcd721ea20)

**Comment by Bawnorton** [comment]
Pause Screen -> Mods -> RuntimeTrims -> Settings. That is if you have modmenu installed, otherwise, you'll need to change the config file and restart. `.minecraft/configs/configurable/runtimetrims.json5`

**Comment by Cindystick** [comment]
![屏幕截图(670)](https://github.com/user-attachments/assets/1700700e-a76a-42d3-be8d-09d04d5c1881)
After opening the legacy renderer, I found that there was no difference, and the rendering effect was still the same

**Comment by Bawnorton** [comment]
Neat, so it all is working?

**Comment by Cindystick** [comment]
I think so, everything functions and rendering are normal

**Comment by Cindystick** [comment]
Sorry but there is one more thing to consider.
Can you consider adding compatibility with trinkets modules?
The trinkets module has added more equipment slots for players, such as belt slots (located at the leg guard) 
elytra slots (located at the breastplate), shulker box slots (also located at the breastplate).
Currently elytra with armor trims can only play the function of armor trims when it is used in the vanilla breastplate field.
Can items be placed in the extra  elytra slot while the added functions of the elytratrims module can also be used normally?

**Comment by Bawnorton** [comment]
I'll look into it

**Comment by Cindystick** [comment]
Thank you, it's a great honor
