### ISSUE TITLE
changelog never updates

### ISSUE THREAD

**Issue by VaporeonScripts** [Bawnorton/BetterTrims#82]
its been alot of updates since the changelog file updated, its stuck on 2.3.2 lol (hoping u could fix it xD )

**Comment by Bawnorton** [comment]
Yeah it's just linking to the wrong one, I'll update my build script

**Comment by VaporeonScripts** [comment]
alright,ty!

**Comment by VaporeonScripts** [comment]
same happens for all the trims, stuck on 4.0.8 while 5.0.0 is out
