### ISSUE TITLE
missing tags? neoforge 1.21.1

### ISSUE THREAD

**Issue by VaporeonScripts** [Bawnorton/BetterTrims#84]
https://mclo.gs/VUIPqaw

**Comment by VaporeonScripts** [comment]
![image](https://github.com/user-attachments/assets/3d888651-80f1-4d9b-a4f8-f75cadf68ec9)

**Comment by Bawnorton** [comment]
This is caused by missing common tags which can only happen if something else breaks them and will break just about most of the game. Also the crash is unrelated to bettertrims
