### ISSUE TITLE
[Crash] Game crash when using Bettertrims and Iris

### ISSUE THREAD

**Issue by Anonyku05** [Bawnorton/BetterTrims#89]
Hi, i'm on 1.20.4 with both latest Bettertrims and FabricAPI/Loader version, and the game crash once mods are loaded when Iris and Bettertrims are installed together, here is the crash log: https://mclo.gs/VSWwDGU

I tried only using Iris and Bettertrims alone (along with Sodium and Fabric API) abd the crash persist

**Comment by Bawnorton** [comment]
update better trims

**Comment by Anonyku05** [comment]
Just realized the mod is technically not even available for 1.20.4 and i messed with the json file to make it work, guess i'll just stop using it
